// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmRZL3JVdL_cxwtZ5DM4nCYSe8f3pZiSE',
    appId: '1:374744735161:web:619cb81dc7dcaa447c6a68',
    messagingSenderId: '374744735161',
    projectId: 'flutter-projects-bcf78',
    authDomain: 'flutter-projects-bcf78.firebaseapp.com',
    storageBucket: 'flutter-projects-bcf78.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCF5I1O2f7uQ-wh1GdTUoLi-4hYuAaSsuU',
    appId: '1:374744735161:android:b9cf4e47e9ddac2e7c6a68',
    messagingSenderId: '374744735161',
    projectId: 'flutter-projects-bcf78',
    storageBucket: 'flutter-projects-bcf78.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4GSsNI4ibUL2AhQzWv7h6T7OijzBc8YA',
    appId: '1:374744735161:ios:945e38cc929d82907c6a68',
    messagingSenderId: '374744735161',
    projectId: 'flutter-projects-bcf78',
    storageBucket: 'flutter-projects-bcf78.firebasestorage.app',
    iosBundleId: 'com.example.pushApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC4GSsNI4ibUL2AhQzWv7h6T7OijzBc8YA',
    appId: '1:374744735161:ios:945e38cc929d82907c6a68',
    messagingSenderId: '374744735161',
    projectId: 'flutter-projects-bcf78',
    storageBucket: 'flutter-projects-bcf78.firebasestorage.app',
    iosBundleId: 'com.example.pushApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDmRZL3JVdL_cxwtZ5DM4nCYSe8f3pZiSE',
    appId: '1:374744735161:web:98e681dcee5529b57c6a68',
    messagingSenderId: '374744735161',
    projectId: 'flutter-projects-bcf78',
    authDomain: 'flutter-projects-bcf78.firebaseapp.com',
    storageBucket: 'flutter-projects-bcf78.firebasestorage.app',
  );
}
